name: Prototype Pixi Testing

# For testing: I'm looking for the best way to deploy our workflows
# Working theory: specifying jobs is better than having a big workflow with many inputs
# Result: we can easily separate workflows by permissions and keep most builds read-only

on:
  push:
    branches:
      - "master"
  pull_request:
  release:
    types:
      - created

jobs:
  pre-commit:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/pre-commit.yml@ca2b211586cb0aefc872de9a1f16680a733c965d

  unit-tests:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-pixi-test.yml@ca2b211586cb0aefc872de9a1f16680a733c965d

  packaging-tests:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-uv-build.yml@ca2b211586cb0aefc872de9a1f16680a733c965d
    with:
      package-name: "pcdswidgets"

  pypi-upload:
    permissions:
      id-token: write
    needs: packaging-tests
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-uv-publish.yml@ca2b211586cb0aefc872de9a1f16680a733c965d

  docs-build:
    permissions:
      contents: read
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-pixi-docs-build.yml@ca2b211586cb0aefc872de9a1f16680a733c965d

# TODO: not existing yet
#  docs-upload:
#    permissions:
#      pages: write
#      id-token: write
#    needs: docs-build
#    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
#    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-docs-upload.yml@ca2b211586cb0aefc872de9a1f16680a733c965d
